[package]
name = "hello"
version = "0.1.0"
authors = ["Jonathan Agarrado <jet320boy@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
